<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TDestino extends Model
{
    protected $table = "tdestinos";

    public function getRouteKeyName()
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return "url";
    }

    public function paquetes_destinos()
    {
        return $this->hasMany(TPaqueteDestino::class, 'iddestinos');
    }
    public function hotel_destinos()
    {
        return $this->hasMany(THotelDestino::class, 'iddestinos');
    }
    public function destino_imagen()
    {
        return $this->hasMany(TDestinoImagen::class, 'iddestinos');
    }

    public function paquetes()
    {
        return $this->belongsToMany(
            TPaquete::class,
            'tpaquetesdestinos',
            'iddestinos',  // FK a tdestinos
            'idpaquetes'   // FK a tpaquetes
        );
    }
}
